"""Generate a model card (governance artifact) from metrics.json.

Attached to every release — answers "what is this model, what data,
what performance, what limits" for auditors and future engineers.
"""
import json
import sys
from datetime import UTC, datetime
from pathlib import Path


def main() -> int:
    metrics = json.loads(Path("model/metrics.json").read_text())
    card = f"""# Model Card — breast-cancer-classifier

**Generated:** {datetime.now(UTC).isoformat(timespec="seconds")}

## Lineage
| | |
|---|---|
| Git commit | `{metrics["git_sha"]}` |
| Data hash | `{metrics["data_hash"]}` |
| Training rows | {metrics["n_train"]} |
| Test rows | {metrics["n_test"]} |
| Parameters | `{json.dumps(metrics["params"])}` |

## Performance (held-out test set)
| Metric | Value |
|---|---|
| AUC | {metrics["auc"]} |
| Accuracy | {metrics["accuracy"]} |

## Intended use
Binary classification demo for an MLOps pipeline. Not for clinical use.

## Monitoring
- PSI drift gate: alert threshold 0.2 per feature (`src/drift_check.py`)
- Evidently drift report generated by the scheduled drift workflow
- Serving exposes prediction-confidence histograms at `/metrics`

## Promotion gate
AUC must be >= 0.95 and must not regress more than 0.005 below the
current production baseline (`src/gate.py`).
"""
    Path("model/MODEL_CARD.md").write_text(card)
    print("model card written to model/MODEL_CARD.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
